---
- name: Configure local YUM repositories on managed nodes
  hosts: all
  become: yes

  tasks:
    - name: Create BaseOS repository
      yum_repository:
        name: BaseOS
        description: Base OS Repo
        baseurl: file:///mnt/BaseOS/
        gpgcheck: yes
        enabled: no
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux-9

    - name: Create AppStream repository
      yum_repository:
        name: AppStream
        description: AppStream Repo
        baseurl: file:///mnt/AppStream/
        gpgcheck: yes
        enabled: no
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux-9
