---
- name: Configure Database
  hosts: balancer
  become: true
  gather_facts: true

  vars_files:
    - vars/db.yml

  tasks:
    - name: Install MariaDB server
      ansible.builtin.yum:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: Ensure MariaDB service is running and enabled
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Ensure MariaDB Python bindings are installed
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present

    - name: Create MariaDB database
      community.mysql.mysql_db:
        name: "{{ DB_name }}"
        state: present
        login_user: root4
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create MariaDB user
      community.mysql.mysql_user:
        name: "{{ DB_user }}"
        password: "{{ DB_pass }}"
        priv: "{{ DB_name }}.*:ALL"
        state: present
        login_user: root
        login_unix_socket: /var/lib/mysql/mysql.sock
