---
  - name: install Database server
    hosts: dev
    become: true
    gather_facts: false


    vars_files:
      - vars/db.yml


    tasks:
       - name: install MariaDB
         ansible.builtin.yum:
            name: mariadb
            state: present
            update_cache: yes

       - name: Check if Mariadb is running and enabled
         ansible.builtin.service:
             name: mariadb
             state: started
             enabled: yes

        
    - name: Ensure MariaDB Python bindings are installed (for future tasks)
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present

    - name: Create MariaDB database
      community.mysql.mysql_db:
        name: "{{ DB_name }}"
        state: present
        login_user: root

    - name: Create MariaDB user
      community.mysql.mysql_user:
        name: "{{ DB_user }}"
        password: "{{ DB_pass }}"
        priv: "{{ DB_name }}.*:ALL"
        state: present
        login_user: root 
